directories:
- base: /home/sean/sourcecode
  subs:
  - rust
- /home/sean/sourcecode/crystal
exec: code -r
show_files: true
show_hidden: false
show_icons: true
ui_provider: wofi
wofi:
  config: /home/sean/.config/wofi/projects/config
  stylesheet: /home/sean/.config/wofi/projects/style.css
