[browse.ui]
exec = "rofi -dmenu -theme venture.rasi -markup-rows"
format = "{icon} {name}"
supports.pango = true

[browse.profiles.home]
exec = "xdg-open {path}"
paths = [
	"~/Documents",
	"~/Downloads/*",
	"~/Pictures/**/*",
	"~/Videos/*",
]

exclude = ["*.mobi", "*.zip", "*/Screenshots/*"]
show.directories = false

[browse.profiles.code]
exec = "code -r {path}"
paths = [
	"~/sourcecode/*",
	"~/sourcecode/school/**/*",
	"~/sourcecode/atomicjolt/*",
	"~/sourcecode/atomicjolt/otc/*"
]

exclude = ["school", "*.zip", "*otc"]
show.files = false


[browse.profiles.stress]
exec = "code -r {path}"
paths = ["./files/**/*"]

show.files = false

[quicklaunch]
exec = "code -r {path}"

[quicklaunch.ui]
exec = "rofi -dmenu -theme venture.rasi -markup-rows -sep '|' -eh 2"
format = "{icon} {name}\n<span size='smaller' weight='light'>{details}</span>"
seperator = "|"
supports.pango = true

[[quicklaunch.entries]]
name = "arc"
path = "~/sourcecode/arc"
icon = ":py:"
details = ":py: python"

[[quicklaunch.entries]]
name = "Comic Site"
path = "~/sourcecode/comic-site"
icon = "󱗖"
details = ":js: javascript, svelte"

[[quicklaunch.entries]]
name = "Sway"
path = "~/.config/sway/config"
icon = "\uF2D2"
details = ":config: config"

[[quicklaunch.entries]]
name = "Venture"
path = "~/sourcecode/venture"
icon = "\uE771"
details = ":py: python"
